# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-12 11:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('PUMA', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherstation',
            name='picture',
            field=models.ImageField(default=datetime.datetime(2016, 3, 12, 11, 59, 54, 142946, tzinfo=utc), upload_to=''),
            preserve_default=False,
        ),
    ]
