# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-12 12:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PUMA', '0002_weatherstation_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weatherstation',
            name='picture',
        ),
    ]
