# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-12 12:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('PUMA', '0004_area_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='picture',
        ),
        migrations.AddField(
            model_name='weatherstation',
            name='picture',
            field=models.ImageField(default=datetime.datetime(2016, 3, 12, 12, 50, 35, 304682, tzinfo=utc), upload_to=''),
            preserve_default=False,
        ),
    ]
