# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-22 20:37
from __future__ import unicode_literals

from django.db import migrations, models
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('PUMA', '0005_auto_20160312_0650'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('geom', djgeojson.fields.LineStringField()),
                ('description', models.TextField()),
                ('color', models.TextField()),
            ],
        ),
    ]
