# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-22 20:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('PUMA', '0006_lines'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='picture',
            field=models.ImageField(default=datetime.datetime(2016, 4, 22, 20, 46, 13, 708082, tzinfo=utc), upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lines',
            name='picture',
            field=models.ImageField(default=datetime.datetime(2016, 4, 22, 20, 46, 20, 133870, tzinfo=utc), upload_to=''),
            preserve_default=False,
        ),
    ]
