# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-22 21:15
from __future__ import unicode_literals

from django.db import migrations
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('PUMA', '0007_auto_20160422_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lines',
            name='geom',
            field=djgeojson.fields.MultiLineStringField(),
        ),
    ]
