# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-24 17:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PUMA', '0008_auto_20160422_1615'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lines',
        ),
        migrations.RemoveField(
            model_name='area',
            name='picture',
        ),
    ]
