# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-24 17:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('PUMA', '0009_auto_20160424_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('geom', djgeojson.fields.MultiLineStringField()),
                ('picture', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('color', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='area',
            name='picture',
            field=models.ImageField(default=datetime.datetime(2016, 4, 24, 17, 39, 44, 197072, tzinfo=utc), upload_to=''),
            preserve_default=False,
        ),
    ]
