# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-09 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PUMA', '0014_auto_20160518_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='approved_comment',
            field=models.BooleanField(default=True),
        ),
    ]
