# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 14:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ExioVisuals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherstation',
            name='name',
            field=models.TextField(default=datetime.datetime(2016, 2, 26, 14, 31, 19, 204005, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
