# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 15:12
from __future__ import unicode_literals

from django.db import migrations
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ExioVisuals', '0002_weatherstation_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherstation',
            name='geom',
            field=djgeojson.fields.PolygonField(),
        ),
    ]
