# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 15:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ExioVisuals', '0003_auto_20160227_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherstation',
            name='popup',
            field=models.TextField(default=datetime.datetime(2016, 2, 27, 15, 31, 31, 206778, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='weatherstation',
            name='geom',
            field=djgeojson.fields.PointField(),
        ),
    ]
