# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 16:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ExioVisuals', '0004_auto_20160227_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherstation',
            name='picture',
            field=models.ImageField(default=datetime.datetime(2016, 2, 27, 16, 37, 33, 805210, tzinfo=utc), upload_to=b''),
            preserve_default=False,
        ),
    ]
