# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 16:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ExioVisuals', '0005_weatherstation_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherstation',
            name='description',
            field=models.TextField(default=datetime.datetime(2016, 2, 27, 16, 39, 24, 569212, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
