# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 16:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExioVisuals', '0006_weatherstation_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weatherstation',
            name='picture',
        ),
    ]
