# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 17:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ExioVisuals', '0010_auto_20160227_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='colors',
            field=models.TextField(default=datetime.datetime(2016, 2, 27, 17, 32, 21, 381302, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
