# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 17:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ExioVisuals', '0012_remove_area_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='colour',
            field=models.TextField(default=datetime.datetime(2016, 2, 27, 17, 58, 54, 632713, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
