# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 18:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExioVisuals', '0013_area_colour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='colour',
        ),
    ]
