# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 16:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ExioVisuals', '0014_remove_area_colour'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='color',
            field=models.TextField(default=datetime.datetime(2016, 2, 28, 16, 13, 44, 215838, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
