# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-02 14:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExioVisuals', '0021_auto_20160402_0845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selection',
            name='categories',
        ),
        migrations.DeleteModel(
            name='Selection',
        ),
    ]
