# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-02 14:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExioVisuals', '0023_selection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selection',
            name='name',
        ),
    ]
