# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-15 12:42
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ExioVisuals', '0024_remove_selection_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=100, overwrite=True, populate_from='name'),
        ),
    ]
