# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-17 11:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ExioVisuals', '0030_years'),
    ]

    operations = [
        migrations.CreateModel(
            name='Selection3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Substance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=100)),
                ('url', models.TextField(editable=False)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='ExioVisuals.Substance')),
            ],
            options={
                'ordering': ('tree_id', 'lft'),
                'verbose_name_plural': 'FancyTreeSubstance',
            },
        ),
        migrations.AddField(
            model_name='selection3',
            name='substances',
            field=models.ManyToManyField(to='ExioVisuals.Substance'),
        ),
        migrations.AlterUniqueTogether(
            name='substance',
            unique_together=set([('name', 'slug', 'parent')]),
        ),
    ]
