# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-09 11:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ExioVisuals', '0032_auto_20160517_0628'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='local',
            field=models.CharField(default=datetime.datetime(2016, 6, 9, 11, 34, 45, 49555, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='level',
            field=models.CharField(max_length=200),
        ),
    ]
