# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-27 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExioVisuals', '0035_auto_20160609_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='lwst_level',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='lwst_level',
            field=models.BooleanField(default=False),
        ),
    ]
