# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-27 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExioVisuals', '0036_auto_20160627_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='local',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='lvl',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
